apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: bogdanpaul15/kafka-consumer:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
            - name: KAFKA_TOPIC
              value: "my-topic"
            - name: KAFKA_GROUP_ID
              value: "my-consumer-group"
            - name: OPENSEARCH_ADDRESSES
              value: "opensearch.kafka.svc:9200"
            - name: CONSUMER_BATCH_SIZE
              value: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  namespace: kafka
  labels:
    app: kafka-consumer
spec:
  type: ClusterIP
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080